# EN 625.250 - Linear Algeba, Linear Algebra (scipy.linalg)
Mainly cover Chapter 7 and 8, on Linear Algeba  
[Scipy Tutorial, Scipy v1.6.3, on scipy.linalg](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html) 

Tips: 
- put 2 empty block in the end of sentence. Press enter then you get a new line in JuputerNotebook cell
- ESC enter command mode, m for markdown

In [2]:
import numpy as np
from scipy import linalg

## numpy.matrix vs 2-D numpy.ndarray
numpy.matrix > numpy.ndarray, but may lead to confusion of which class is being used. 

In [14]:
# Examples in numpy
A = np.mat('[1 2;3 4]')
print("Matrix A:\n", A)
print("Matrix A inverse:\n", A.I)
b = np.mat('[5 6]')
print("Matrix b:\n", b)
print("Matrix b transpose:\n", b.T)
print("Matrix A multiple b^T:\n", A*b.T)

Matrix A:
 [[1 2]
 [3 4]]
Matrix A inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix b:
 [[5 6]]
Matrix b transpose:
 [[5]
 [6]]
Matrix A multiple b^T:
 [[17]
 [39]]


In [21]:
# Example in Scipy.linalg
# scipy.linalg operations can be applied equally to numpy.matrix or to 2D numpy.ndarray objects.
A = np.array([[1,2],[3,4]])
A_inv = linalg.inv(A)

b = np.array([[5,6]]) #2D array

A*b #not matrix multiplication!
A.dot(b.T) #matrix multiplication

c = np.array([5,6]) #1D array

# c.T  #not matrix transpose!
# A.dot(b)  #does not matter for multiplication

print("Matrix A:\n", A)
print("Matrix A inverse:\n", A_inv)
print("2D array, vector b:\n", b)
print("2D array, vector b^T:\n", b.T)
print("A*b is not matrix multiplication:\n", A*b)
print("Matrix A multiple b^T, A.dot(b.T):\n", A.dot(b.T))
print("1D array, vector c:\n", c)
print("Matrix A multiple c^T still works:\n", A.dot(b.T))

Matrix A:
 [[1 2]
 [3 4]]
Matrix A inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
2D array, vector b:
 [[5 6]]
2D array, vector b^T:
 [[5]
 [6]]
A*b is not matrix multiplication:
 [[ 5 12]
 [15 24]]
Matrix A multiple b^T, A.dot(b.T):
 [[17]
 [39]]
1D array, vector c:
 [5 6]
Matrix A multiple c^T:
 [[17]
 [39]]


## Basic routines
### Inverse

In [25]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A.dot(linalg.inv(A)) #double check

print("Matrix A:\n", A)
print("Matrix A inverse:\n", linalg.inv(A))
print("Check the result, A.dot(linalg.inv(A)):\n", A.dot(linalg.inv(A)))

Matrix A:
 [[1 3 5]
 [2 5 1]
 [2 3 8]]
Matrix A inverse:
 [[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
Check the result, A.dot(linalg.inv(A)):
 [[ 1.00000000e+00 -1.11022302e-16 -6.24500451e-17]
 [ 3.05311332e-16  1.00000000e+00  1.87350135e-16]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]


### Solving a linear system

In [27]:
# Intuitive but slow way - 6 ms
A = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

linalg.inv(A).dot(b)  # slow
A.dot(linalg.inv(A).dot(b)) - b  # check

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("A slower way, linalg.inv(A).dot(b):\n", linalg.inv(A).dot(b))
print("Check the result, A.dot(linalg.inv(A).dot(b)) - b:\n", A.dot(linalg.inv(A).dot(b)) - b)

Matrix A:
 [[1 2]
 [3 4]]
Vector b:
 [[5]
 [6]]
A slower way, linalg.inv(A).dot(b):
 [[-4. ]
 [ 4.5]]
Check the result, A.dot(linalg.inv(A).dot(b)) - b:
 [[0.00000000e+00]
 [1.77635684e-15]]


In [28]:
# A faster way - 4 ms
np.linalg.solve(A, b)  # fast
A.dot(np.linalg.solve(A, b)) - b  # check
print("A faster way, np.linalg.solve(A, b):\n", np.linalg.solve(A, b))
print("Check the result, A.dot(np.linalg.solve(A, b)) - b:\n", A.dot(np.linalg.solve(A, b)) - b)

A faster way, np.linalg.solve(A, b):
 [[-4. ]
 [ 4.5]]
Check the result, A.dot(np.linalg.solve(A, b)) - b:
 [[0.]
 [0.]]


### Finding the determinant

In [29]:
A = np.array([[1,2],[3,4]])

print("Matrix A:\n", A)
print("Determinant of A:\n", linalg.det(A))

Matrix A:
 [[1 2]
 [3 4]]
Determinant of A:
 -2.0


### Computing norm
A wide range of norm definitions are available using different parameters to the order argument of linalg.norm

In [3]:
A=np.array([[1,2],[3,4]])

print("Matrix A:\n", A)
print("Matrix A norm linalg.norm(A):\n", linalg.norm(A))
print("Matrix A norm linalg.norm(A,'fro'), frobenius norm is the default:\n", linalg.norm(A,'fro'))
print("Matrix A norm linalg.norm(A,1), L1 norm (max column sum):\n", linalg.norm(A,1))
print("Matrix A norm linalg.norm(A,-1):\n", linalg.norm(A,-1))
print("Matrix A norm linalg.norm(A,np.inf), L inf norm (max row sum):\n", linalg.norm(A,np.inf))

Matrix A:
 [[1 2]
 [3 4]]
Matrix A norm linalg.norm(A):
 5.477225575051661
Matrix A norm linalg.norm(A,'fro'), frobenius norm is the default:
 5.477225575051661
Matrix A norm linalg.norm(A,1), L1 norm (max column sum):
 6.0
Matrix A norm linalg.norm(A,-1):
 4.0
Matrix A norm linalg.norm(A,np.inf), L inf norm (max row sum):
 7.0


### Solving linear least-squares problems and pseudo-inverses

## Decompositions

### Eigenvalues and Eigenvectors 

In [8]:
A = np.array([[1, 2], [3, 4]])
la, v = linalg.eig(A)
l1, l2 = la

print("eigenvalues: ", l1, l2)   # eigenvalues
print("first eigenvector: ", v[:, 0])   # first eigenvector
print("second eigenvector: ", v[:, 1])   # second eigenvector

print("eigenvectors are unitary: ", np.sum(abs(v**2), axis=0))  # eigenvectors are unitary

v1 = np.array(v[:, 0]).T
print("check the computation: ", linalg.norm(A.dot(v1) - l1*v1))  # check the computation

eigenvalues (-0.3722813232690143+0j) (5.372281323269014+0j)
first eigenvector [-0.82456484  0.56576746]
second eigenvector [-0.41597356 -0.90937671]
eigenvectors are unitary:  [1. 1.]
check the computation:  5.551115123125783e-17


In [5]:
# simply example
A = np.array([[1, 0, 0], 
              [0, 2, 0],
              [0, 0, 3]])
evalue, evector = linalg.eig(A)
print(evalue)
print(evector)

[1.+0.j 2.+0.j 3.+0.j]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# with identical eigenvalues, 5 have 2 evectors (column vector!) [-0.83205029, -0.5547002, 0]^T and [0, 0, 1]^T
A = np.array([[1, 6, 0], 
              [2, 2, 0],
              [0, 0, 5]])
evalue, evector = linalg.eig(A)
print(evalue)
print(evector)

[-2.+0.j  5.+0.j  5.+0.j]
[[-0.89442719 -0.83205029  0.        ]
 [ 0.4472136  -0.5547002   0.        ]
 [ 0.          0.          1.        ]]


In [7]:
# with identical eigenvalues, and linear dependent vector, [1, 0, 0]^T
# So can not inverse. Might transform to Jordan style. 
A = np.array([[6, -2, 1], 
              [0, 4, 0],
              [0, 0, 6]])
evalue, evector = linalg.eig(A)
print(evalue)
print(evector)

[6.+0.j 4.+0.j 6.+0.j]
[[ 1.00000000e+00  7.07106781e-01 -1.00000000e+00]
 [ 0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.33226763e-15]]


### Singular value decomposition

### LU decomposition